// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cpp_MLC
List cpp_MLC(const arma::mat X, const arma::vec Y, const CharacterVector levels);
RcppExport SEXP _tabularMLC_cpp_MLC(SEXP XSEXP, SEXP YSEXP, SEXP levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const CharacterVector >::type levels(levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_MLC(X, Y, levels));
    return rcpp_result_gen;
END_RCPP
}
// cpp_predict
arma::mat cpp_predict(S4 model, arma::mat X);
RcppExport SEXP _tabularMLC_cpp_predict(SEXP modelSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_predict(model, X));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mean
double cpp_mean(arma::vec X);
RcppExport SEXP _tabularMLC_cpp_mean(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mean(X));
    return rcpp_result_gen;
END_RCPP
}
// cpp_quantile
arma::vec cpp_quantile(arma::vec X, arma::vec Y);
RcppExport SEXP _tabularMLC_cpp_quantile(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_quantile(X, Y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tabularMLC_cpp_MLC", (DL_FUNC) &_tabularMLC_cpp_MLC, 3},
    {"_tabularMLC_cpp_predict", (DL_FUNC) &_tabularMLC_cpp_predict, 2},
    {"_tabularMLC_cpp_mean", (DL_FUNC) &_tabularMLC_cpp_mean, 1},
    {"_tabularMLC_cpp_quantile", (DL_FUNC) &_tabularMLC_cpp_quantile, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_tabularMLC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
