// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cpp_MLC
List cpp_MLC(arma::mat X, arma::rowvec Y, CharacterVector levels);
RcppExport SEXP _tabularMLC_cpp_MLC(SEXP XSEXP, SEXP YSEXP, SEXP levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type levels(levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_MLC(X, Y, levels));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tabularMLC_cpp_MLC", (DL_FUNC) &_tabularMLC_cpp_MLC, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_tabularMLC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
