# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_MLC <- function(X, Y, levels) {
    .Call(`_tabularMLC_cpp_MLC`, X, Y, levels)
}

cpp_predict <- function(model, X) {
    .Call(`_tabularMLC_cpp_predict`, model, X)
}

